/*
 * NSwager Test Server API
 *
 * An api used to test NSwager.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using open.api.tool.Client;
using open.api.tool.Model;

namespace open.api.tool.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMainApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// A ping end point.
        /// </summary>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PingDTO</returns>
        PingDTO ApiV2MainPingGet(int operationIndex = 0);

        /// <summary>
        /// A ping end point.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PingDTO</returns>
        ApiResponse<PingDTO> ApiV2MainPingGetWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Hello world end point.
        /// </summary>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserNameDTO</returns>
        UserNameDTO HelloWorld(int operationIndex = 0);

        /// <summary>
        /// Hello world end point.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserNameDTO</returns>
        ApiResponse<UserNameDTO> HelloWorldWithHttpInfo(int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMainApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// A ping end point.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PingDTO</returns>
        System.Threading.Tasks.Task<PingDTO> ApiV2MainPingGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// A ping end point.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PingDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<PingDTO>> ApiV2MainPingGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Hello world end point.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserNameDTO</returns>
        System.Threading.Tasks.Task<UserNameDTO> HelloWorldAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Hello world end point.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserNameDTO)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserNameDTO>> HelloWorldWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMainApi : IMainApiSync, IMainApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MainApi : IMainApi
    {
        private open.api.tool.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MainApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MainApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MainApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MainApi(string basePath)
        {
            this.Configuration = open.api.tool.Client.Configuration.MergeConfigurations(
                open.api.tool.Client.GlobalConfiguration.Instance,
                new open.api.tool.Client.Configuration { BasePath = basePath }
            );
            this.Client = new open.api.tool.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new open.api.tool.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = open.api.tool.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MainApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MainApi(open.api.tool.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = open.api.tool.Client.Configuration.MergeConfigurations(
                open.api.tool.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new open.api.tool.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new open.api.tool.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = open.api.tool.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MainApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public MainApi(open.api.tool.Client.ISynchronousClient client, open.api.tool.Client.IAsynchronousClient asyncClient, open.api.tool.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = open.api.tool.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public open.api.tool.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public open.api.tool.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public open.api.tool.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public open.api.tool.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// A ping end point. 
        /// </summary>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PingDTO</returns>
        public PingDTO ApiV2MainPingGet(int operationIndex = 0)
        {
            open.api.tool.Client.ApiResponse<PingDTO> localVarResponse = ApiV2MainPingGetWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// A ping end point. 
        /// </summary>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PingDTO</returns>
        public open.api.tool.Client.ApiResponse<PingDTO> ApiV2MainPingGetWithHttpInfo(int operationIndex = 0)
        {
            open.api.tool.Client.RequestOptions localVarRequestOptions = new open.api.tool.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = open.api.tool.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = open.api.tool.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "MainApi.ApiV2MainPingGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<PingDTO>("/api/v2/main/ping", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV2MainPingGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// A ping end point. 
        /// </summary>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PingDTO</returns>
        public async System.Threading.Tasks.Task<PingDTO> ApiV2MainPingGetAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            open.api.tool.Client.ApiResponse<PingDTO> localVarResponse = await ApiV2MainPingGetWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// A ping end point. 
        /// </summary>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PingDTO)</returns>
        public async System.Threading.Tasks.Task<open.api.tool.Client.ApiResponse<PingDTO>> ApiV2MainPingGetWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            open.api.tool.Client.RequestOptions localVarRequestOptions = new open.api.tool.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = open.api.tool.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = open.api.tool.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "MainApi.ApiV2MainPingGet";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<PingDTO>("/api/v2/main/ping", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ApiV2MainPingGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Hello world end point. 
        /// </summary>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserNameDTO</returns>
        public UserNameDTO HelloWorld(int operationIndex = 0)
        {
            open.api.tool.Client.ApiResponse<UserNameDTO> localVarResponse = HelloWorldWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Hello world end point. 
        /// </summary>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserNameDTO</returns>
        public open.api.tool.Client.ApiResponse<UserNameDTO> HelloWorldWithHttpInfo(int operationIndex = 0)
        {
            open.api.tool.Client.RequestOptions localVarRequestOptions = new open.api.tool.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = open.api.tool.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = open.api.tool.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "MainApi.HelloWorld";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<UserNameDTO>("/api/v2/main/hello-world", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HelloWorld", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Hello world end point. 
        /// </summary>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserNameDTO</returns>
        public async System.Threading.Tasks.Task<UserNameDTO> HelloWorldAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            open.api.tool.Client.ApiResponse<UserNameDTO> localVarResponse = await HelloWorldWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Hello world end point. 
        /// </summary>
        /// <exception cref="open.api.tool.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserNameDTO)</returns>
        public async System.Threading.Tasks.Task<open.api.tool.Client.ApiResponse<UserNameDTO>> HelloWorldWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            open.api.tool.Client.RequestOptions localVarRequestOptions = new open.api.tool.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = open.api.tool.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = open.api.tool.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "MainApi.HelloWorld";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<UserNameDTO>("/api/v2/main/hello-world", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("HelloWorld", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
