/*
 * NSwager Test Server API
 *
 * An api used to test NSwager.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = open.api.tool.Client.OpenAPIDateConverter;

namespace open.api.tool.Model
{
    /// <summary>
    /// A ping DTO.
    /// </summary>
    [DataContract(Name = "PingDTO")]
    public partial class PingDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PingDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PingDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PingDTO" /> class.
        /// </summary>
        /// <param name="value">The value of the ping (required).</param>
        public PingDTO(string value = default(string))
        {
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for PingDTO and cannot be null");
            }
            this.Value = value;
        }

        /// <summary>
        /// The value of the ping
        /// </summary>
        /// <value>The value of the ping</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PingDTO {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
