/*
 * NSwager Test Server API
 *
 * An api used to test NSwager.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = open.api.tool.Client.OpenAPIDateConverter;

namespace open.api.tool.Model
{
    /// <summary>
    /// A DTO containing user name
    /// </summary>
    [DataContract(Name = "UserNameDTO")]
    public partial class UserNameDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserNameDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UserNameDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UserNameDTO" /> class.
        /// </summary>
        /// <param name="userName">The value of the user name (required).</param>
        public UserNameDTO(string userName = default(string))
        {
            // to ensure "userName" is required (not null)
            if (userName == null)
            {
                throw new ArgumentNullException("userName is a required property for UserNameDTO and cannot be null");
            }
            this.UserName = userName;
        }

        /// <summary>
        /// The value of the user name
        /// </summary>
        /// <value>The value of the user name</value>
        [DataMember(Name = "userName", IsRequired = true, EmitDefaultValue = true)]
        public string UserName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserNameDTO {\n");
            sb.Append("  UserName: ").Append(UserName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
